config/routes.rb
Babyio::Application.routes.draw do
  match "/settings/account" => "settings#account", :as => :settings_account
  match "/settings/password" => "settings#password", :as => :settings_password
  match "/settings/applications" => "settings#apps", :as => :settings_apps

  devise_for :users,
    :controllers => {
      :registrations => "users/registrations",
      :omniauth_callbacks => "users/omniauth_callbacks"
    }

  match "/users/:id" => "users#show", :via => :get, :as => :user

  resources :users do
    resources :babies, :except => :show
  end
  match ":username" => "babies#show", :via => :get, :as => :baby

  scope ":username" do
    resources :posts
  end

  root :to => "home#landing"
end

app/models/baby.rb
class Baby
  include Mongoid::Document
  include Mongoid::Timestamps

  ## Protect against mass-assignment
  attr_accessible :username, :user_id, :first_name, :last_name, :birthday

  ## Baby Details
  field :username,   :type => String, :default => ""
  field :first_name, :type => String, :default => ""
  field :last_name,  :type => String, :default => ""
  field :birthday,   :type => Date, :default => ""

  validates_presence_of :username, :first_name, :last_name, :birthday
  index({ username: 1 }, { unique: true })

  ## Relations
  belongs_to :user
  embeds_many :posts

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :message, :type => String, :default => ""

  mount_uploader :picture, ImageUploader

  embedded_in :baby
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :omniauthable

  ## Protect against mass-assignment
  attr_accessible :email, :password, :remember_me, :name, :avatar, :provider,
    :uid, :remote_avatar_url

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  validates_uniqueness_of :email, :case_sensitive => false

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## user detail
  field :name, :type => String

  field :provider, :type => String
  field :uid,      :type => String

  field :facebook_id
  field :facebook_token

  ## avatar
  mount_uploader :avatar, AvatarUploader

  ## Relations
  has_many :babies

  class << self
    def find_for_facebook_oauth(auth, signed_in_resource = nil)
      user = User.where(:provider => auth.provider, :uid => auth.uid).first
      unless user
        # TODO: Merge existing account
        user = User.create(provider: auth.provider,
                           uid: auth.uid,
                           email: auth.info.email,
                           name: auth.info.name,
                           password:Devise.friendly_token[0, 20],
                           remote_avatar_url: auth.info.image.gsub("square",
                                                                   "large"))
      end

      user
    end
  end

  def babynames
    babies.map(&:username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  def index
    @babies = User.find(params[:user_id]).babies

    respond_to do |format|
      format.json { render json: @babies, status: :ok }
    end
  end

  # GET /:username
  #
  def show
    @baby = Baby.find_by(username: params[:username])

    respond_to do |format|
      format.json { render json: @baby, status: :ok }
    end
  end

  # POST
  #
  def create
    puts current_user
    @baby = current_user.babies.build(params)

    respond_to do |format|
      if @baby.save
        format.json { render json: @baby, status: :ok }
      else
        format.json { render json: @baby.errors, status: :unprocessable_entity}
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /:username
  #
  def index
    baby = Baby.find_by(username: params[:username])
    @posts = baby.posts

    respond_to do |format|
      format.json { render json: @posts, status: :ok }
    end
  end

  # GET /:username/posts/:id
  #
  def show
    baby = Baby.find_by(username: params[:username])
    @post = baby.posts.where(id: params[:id])

    respond_to do |format|
      format.json { render json: @post, status: :ok }
    end
  end

  # PUT /:username/posts/:id
  #
  def update
    baby = Baby.find_by(username: params[:username])
    @post = baby.posts.where(id: params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.json { render json: @post, status: :ok }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  # POST /:username/posts
  #
  def create
    baby = Baby.find_by(username: params[:username])
    @post = baby.posts.build(params)

    respond_to do |format|
      if @post.save
        format.json { render json: @post, status: :ok }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /:username/posts/:id
  #
  def destroy
    baby = Baby.find_by(username: params[:username])
    @post = baby.posts.find_by(id: params[:id])
    @post.destroy

    respond_to do |format|
      format.json { render json: @post, status: :ok }
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!

  def account
    @user = current_user
  end

  def password
    if request.post?
      @user = current_user

      updated = false
      if @user.valid_password? params[:current_password]
        password = params[:password]
        password_confirmation = params[:password_confirmation]
        if !password.blank? and password == password_confirmation
          if @user.update_attributes(password: password)
            flash[:notice] = "Password updated successfully."
            sign_in(@user, :bypass => true)
            updated = true
          end
        end

        flash[:error] = "Passwords do not match." unless updated
      else
        flash[:error] = "Invalid password."
      end

      redirect_to settings_password_url
    end
  end

  def apps
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"],
                                         current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success",
        :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
    @no_header = true
  end

  def create
    super
    # TODO track user creation
    # TODO send welcome email
  end

  def edit
    redirect_to settings_account_url
  end

  def update
    respond_to do |format|
      if current_user.update_attributes(params[:user])
        format.html {
          flash[:notice] = "Account successfully updated."
          redirect_to settings_account_url
        }
        format.json { render json: @user, status: :ok }
      else
        format.html {
          flash[:error] = "Account update unsuccessful. Please try again later."
          render :action => :edit
        }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user.nil?
      redirect_to root_path
    end

    @user = current_user
    respond_to do |format|
      if @user
        @babies = @user.babies
        format.json
      else
        format.json { render json: {}, status: :not_found }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/landing.html.haml
%h2 Hello world

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  %nav.navbar-inner
    .container-fluid
      = link_to "Baby.io", root_path, :class => 'brand'
      %ul.nav
        - if !current_user
          %li= link_to "Stream", "/stream"
        - elsif current_user.babies.length == 1
          %li= link_to "Stream", "/#/stream/#{current_user.babies.first.username}"
        - else # More than 1 baby
          %li.dropdown
            %a.dropdown-toggle{ :"data-toggle" =>"dropdown",
              :href => "#" }
              Stream
              %b.caret
            %ul.dropdown-menu
              - current_user.babies.each do |baby|
                %li= link_to "#{baby.first_name} #{baby.last_name}", "/#/stream/#{baby.username}"

        %li= link_to "Photos", "/photos"
      %ul.nav.pull-right
        - if user_signed_in?
          #user-id{ :value => "#{current_user.id}" }
          %li.dropdown
            %a.dropdown-toggle{ :"data-toggle" =>"dropdown",
              :href => "#menu1" }
              = current_user.email
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "Account", settings_account_path
              %li
                = link_to "Password", settings_password_path
              %li
                = link_to "Apps", settings_apps_path
              %li
                = link_to "Logout", destroy_user_session_path
        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Sign up", new_user_registration_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert fade in alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "Baby.io"
    %meta{ :charset => "utf-8" }
    %meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }
    %meta{ :name => "viewport",
           :content => "width=device-width, initial-scale=1, maximum-scale=1" }
    %meta{ :content => "Baby.io", :name => "description" }
    %meta{ :content => "Baby.io", :name => "author" }

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    - unless @no_header
      = render "layouts/header"
    #main{ :role => "main" }
      .container-fluid
        .row-fluid
          .sidebar.span3
          .content.span9
            = render "layouts/messages"
            = yield
            %footer

app/views/settings/_nav.html.haml
%ul.nav.nav-pills.nav-stacked
  %li{ :class => "#{"active" if controller.action_name == "account"}" }
    %a{ :href => settings_account_url }
      %i.icon-user
      Account
  %li{ :class => "#{"active" if controller.action_name == "password"}" }
    %a{ :href => settings_password_url }
      %i.icon-key
      Password
  %li{ :class => "#{"active" if controller.action_name == "apps"}" }
    %a{ :href => settings_apps_url }
      %i.icon-cloud
      Apps

app/views/settings/account.html.haml
#settings-account
  .page-header
    %h1 Settings

  .row
    .span2
      = render "settings/nav"

    .span10
      = form_for :user, :url => registration_path(:user),
        :html => { :method => :put, :class => "form-horizontal well" } do |f|
        %fieldset
          .control-group
            %label.control-label Profile picture
            .controls
              = image_tag @user.avatar
              = f.file_field :avatar
          %hr
          .control-group
            %label.control-label Name
            .controls
              = f.text_field :name
          .control-group
            %label.control-label Email
            .controls
              = f.text_field :email
          .form-actions
            %button.btn.btn-primary.btn-large Save

app/views/settings/apps.html.haml
#settings-applications
  .page-header
    %h1 Applications

  .row
    .span2
      = render "settings/nav"

    .span10

app/views/settings/password.html.haml
#settings-password
  .page-header
    %h1 Change Password

  .row
    .span2
      = render "settings/nav"

    .span10
      = form_for :user, :url => settings_password_url,
        :html => { :class => "form-horizontal well" } do |f|
        %fieldset
          = f.hidden_field :reset_password_token
          .control-group
            %label.control-label Current password
            .controls
              = password_field_tag :current_password, nil
              %p.help-block
                = link_to "Forgot your password?", new_password_path(:user)
          .control-group
            %label.control-label New password
            .controls
              = password_field_tag :password, nil
          .control-group
            %label.control-label Confirm new password
            .controls
              = password_field_tag :password_confirmation, nil
          .form-actions
            %button.btn.btn-primary.btn-large Save